### ISSUE TITLE
"Getting Started" section treats "RedirectUris" and "PostLogoutRedirectUris" as List<Uri> instead of List<string>

### ISSUE THREAD

**Issue by leastprivilege** [thinktecture/Thinktecture.IdentityServer.v3.Documentation#11]
In the "Getting Started" tutorial, the "Adding Logout" section includes

    RedirectUris = new List<Uri>
    {
        new Uri("https://localhost:44319/")
    },
    PostLogoutRedirectUris = new List<Uri>
    {
        new Uri("https://localhost:44319/")
    }
This doesn't compile, they should both be List<string> instead.

**Comment by RPrimrose** [comment]
There's the same problem in the "Registering a Web API Client" section a bit further down the page as well.

**Comment by leastprivilege** [comment]
fixed. thanks
