### ISSUE TITLE
Using AD to provide identity

### ISSUE THREAD

**Issue by mr-miles** [thinktecture/Thinktecture.IdentityServer.v3.Documentation#26]
Hi,

I have some services and clients, both web-based and wpf, which run in an intranet environment.  I want to centralise authorization into an identity service, with the clients and services using OAuth/claims to allow/deny actions and/or determine what is allowed.  IdentityServer looked like a good fit as I can write some code to produce whatever claims the apps need, keep this logic in one place, and the whole lot will play nicely together.

But ... the user credentials and some basic roles are all stored in active directory, and I'm struggling to see where this fits in exactly to the whole scheme.

FIrst idea was to write a custom user store, and wrap the authorization endpooint in winauth.  Then when the apps redirect to the authorization endpoint, rather than showing a login screen I can negotiate winauth and grant a token based on this identity.  From the interface docs the pre-authenticate method looked to be the right place to do this, but it doesn't have access to any request headers over and above the message so it can't be done (though it sounded like it should be possible).

Next idea was to treat the winauth bit like an External Identity Provider, and make some separate endpoint that turned a windows identity into a token.  But it seemed like this might be making a meal out of the whole thing!

What is the least resistance way to produce this sort of integration?

Thanks in advance for any pointers!

**Comment by brockallen** [comment]
Look into the user service: https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/advanced/userService.html. This is the custom code that allows you to map from the user storage (AD) to tokens that IdentityServer issues.

**Comment by jpoley** [comment]
I have a related question / request in having a provided example with AD/ADFS integration for identity / claims integrating into IS.v3 and having IS.v3 provide a JWT to various applications.  I can only imagine that this is a common use case.

**Comment by leastprivilege** [comment]
We have support for ADFS. Check the docs about external authentication - it deals specifically with WS-Federation.
