### ISSUE TITLE
Possible Cert Issues

### ISSUE THREAD

**Issue by Convolved** [thinktecture/Thinktecture.IdentityServer.v3.Documentation#31]
I’ve tried everything and still can’t get the mvcAuth and simpleAuth samples working locally.  I’ve installed the certs, I’ve loaded certs from local bin(I know it's not necessary).  The only thing that works is not to require SSL.  According to the exceptions, Windows 8.1 is refusing to keep a secure connection alive.  Previous errors also indicated it had to do with certificate validation.

**Comment by leastprivilege** [comment]
SSL and the signing cert are unrelated.

Your IIS (Express) must be set up correctly for SSL. This is a pre-req for doing the walkthroughs

**Comment by Convolved** [comment]
Hi Dominick,

                I finally got it working.  My main issue was the http listener and request were not matching the machine name on the Cert.

Thank you for your assistance,

Erhan Atesoglu

**Comment by ronnieoverby** [comment]
God help you (and by you, I mean me) if you don't know how to configure SSL for OWIN self host. After following [this guidance](http://weblog.west-wind.com/posts/2013/Sep/23/Hosting-SignalR-under-SSLhttps) identity server doesn't even respond to requests anymore.
