### ISSUE TITLE
MvcOwinWsFederation Client Sample getting 404 Error

### ISSUE THREAD

**Issue by flightpath** [thinktecture/Thinktecture.IdentityServer.v3.Documentation#33]
The MvcOwinWsFederation Client Sample is getting a 404 Error. Looking at the Identity Server V3 code it seems that the endpoint to support wsfed has not been implemented. Has anyone else got this working? I was hoping to use v3 to support SharePoint 2013 but it looks like I will have to default to v2. Thks.

**Comment by brockallen** [comment]
You need to run the WS-Fed host from the WS-Fed repository. The one from Core does not have the WS-Fed plugin, as you said.

**Comment by flightpath** [comment]
Thank you. That worked.
