### ISSUE TITLE
additional login parameters

### ISSUE THREAD

**Issue by gri4** [thinktecture/Thinktecture.IdentityServer.v3.Documentation#34]
Hello, thank you for the perfect product. A couple of questions, please.
1) I need to send some additional information (in particular - available login option (user/password/social/adfs) from my client to identity server login page). Would you recommend the best way to do it?
2) based on this information i have to show/hide login options. I have an idea to hide not required controls at login view. Is there a better way?
Thank you

**Comment by leastprivilege** [comment]
Available login options are configured per client (IdentityProviderRestrictions) and EnableLocalLogin.
